apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metadata.fullname" . }}
  labels:
  {{- include "metadata.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{.Files.Get "files/config.yaml" | nindent 6 }}
