apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.fullname" . }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.grpcservice.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "metadata.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata.fullname" . }}
  labels:
    {{- include "metadata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodeportService.type }}
  ports:
    - port: {{ .Values.nodeportService.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.grpcservice.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "metadata.selectorLabels" . | nindent 4 }}

